/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelos.Calculadora;
import Modelos.LectorArchivoDeEntrada;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lopez
 */
public class Ventana extends javax.swing.JFrame {

    private Calculadora calculadora;
    private JFileChooser fc;
    private File file;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrirArchivo3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAbrirArchivo3.setText("Seleccionar archivo de texto");
        btnAbrirArchivo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnAbrirArchivo3)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(btnAbrirArchivo3)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArchivo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivo3ActionPerformed
        comprobarArhivo();
    }//GEN-LAST:event_btnAbrirArchivo3ActionPerformed

    public void comprobarArhivo(){
        fc = new JFileChooser();

        FileNameExtensionFilter fne = new FileNameExtensionFilter(".txt", "txt");

        fc.setFileFilter(fne);
        fc.showOpenDialog(this);
        file = fc.getSelectedFile();
        LectorArchivoDeEntrada l = new LectorArchivoDeEntrada(file);
        calculadora.setLector(l);
        
        try {
            getCalculadora().calcular();
            getCalculadora().calcular();
            JOptionPane.showMessageDialog(this, "Archivo creado");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "El arhivo seleccionado no se puede abrir.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnAbrirArchivo1;
    private javax.swing.JButton btnAbrirArchivo2;
    private javax.swing.JButton btnAbrirArchivo3;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the calculadora
     */
    public Calculadora getCalculadora() {
        return calculadora;
    }

    /**
     * @param calculadora the calculadora to set
     */
    public void setCalculadora(Calculadora calculadora) {
        this.calculadora = calculadora;
    }
}
